name: Verilog Simulation CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - src/**
      - tb/**
      - .github/workflows/**
      - Dockerfile
  pull_request:
    branches:
      - main
      - master
    paths:
      - src/**
      - tb/**
      - .github/workflows/**

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3
        name: docker container buildx
        with:
          driver: docker-container

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          provenance: false
          tags: kr-dev:ci
          load: true

      - name: Check verilator version
        run: |
          docker run --rm -v ${{ github.workspace }}:/project kr-dev:ci bash -lc "verilator --version && verilator --help | head -n 20"

      - name: Run unit tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project kr-dev:ci pytest -q