name: Verilog Simulation CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - src/**
      - tb/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
      - master
    paths:
      - src/**
      - tb/**
      - .github/workflows/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3
        name: docker container buildx
        with:
          driver: docker-container

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          provenance: false
          tags: kr-dev:ci

      - name: Lint Verilog
        run: |
          docker run --rm kr-dev:ci verible-verilog-lint src/*.v

      - name: Run unit tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/project kr-dev:ci make sim